### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by tlin-taolin** [LINs-lab/cluster_tutorial#1]
cannot use the provided user_name/password to access the `login.lins.lab` or `lins.lab`

@DmitriZhao and @sp12138 could you please double-check which part is broken?

**Comment by sp12138** [comment]
I could fix it today.-------- 原始邮件 --------发件人： Tao Lin ***@***.***>日期： 2022年12月3日周六 下午1:53收件人： LINs-lab/cluster_tutorial ***@***.***>抄送： sp12138 ***@***.***>, Mention ***@***.***>主    题： [LINs-lab/cluster_tutorial] login issue (Issue #1)
cannot use the provided user_name/password to access the login.lins.lab or lins.lab
@DmitriZhao and @sp12138 could you please double-check which part is broken?
