### ISSUE TITLE
cannot push docker image to harbor (after login succeeded)

### ISSUE THREAD

**Issue by tlin-taolin** [LINs-lab/cluster_tutorial#11]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/7805823/208569502-d864b461-63c9-477d-bdd1-65d96937bac7.png">

**Comment by DmitriZhao** [comment]
I have updated the admin's manual [here](https://github.com/LINs-lab/cluster_setup/blob/main/docs/02_User_Management.md#create-and-configure-a-harbor-account).

**Comment by tlin-taolin** [comment]
thanks :) it fixed the issue
