### ISSUE TITLE
base environment 

### ISSUE THREAD

**Issue by haobo-song** [LINs-lab/cluster_tutorial#12]
Hello, I find that current determineai base environment cuda-11.3-pytorch-1.10-tf-2.8-gpu-0.19.4 doesn't contain tmux. Since this environment can meet most requirement, is it possible to add tmux into this base environment(needs sudo) so that we don't need to create our own environment in most cases?

**Comment by DmitriZhao** [comment]
Here it is:

`harbor.lins.lab/determinedai/environments:cuda-11.3-pytorch-1.10-tf-2.8-gpu-0.19.4-tmux`

[Link to Harbor](https://harbor.lins.lab/harbor/projects/2/repositories/environments/artifacts-tab/artifacts/sha256:ad5257f9d1b4897e761e6ad05026dfb0ea38c276f855c3134f55484c4499a1a1)

[Dockerfile](https://github.com/LINs-lab/cluster_tutorial/blob/main/examples/determined-tmux/Dockerfile)
