### ISSUE TITLE
Configure Prometheus with cAdvisor, and dcgm-exporter

### ISSUE THREAD

**Issue by tlin-taolin** [LINs-lab/cluster_tutorial#13]
As mentioned in [this link](https://docs.determined.ai/latest/integrations/prometheus/prometheus.html?highlight=grafana), Determined provides a Prometheus endpoint that contains mappings between internal task, GPU, and container definitions, which are used by Prometheus to collect relevant metrics on a cluster running Determined. 

Ideally, we would like to have a monitor for e.g. every 5 mins to kill idle jobs for more than 1h, using the metrics provided by Prometheus.

It is not an urgent task, but it would be very appreciated if you could configure this workflow @DmitriZhao (once you have time).

**Comment by DmitriZhao** [comment]
All the prometheus endpoints (node-exporter, cAdvisor and DeterminedAI) have been added to Prometheus in the commit https://github.com/LINs-lab/cluster_setup/commit/ed9090ef749880d37a6802507e39ad750d4b249e.

Although Determined-AI's [det-state-metrics](https://gpu.lins.lab/prom/det-state-metrics) (to view it in your browser you need to log in to https://gpu.lins.lab first) provides enough information about tasks and containers, the [official document](https://docs.determined.ai/latest/integrations/prometheus/prometheus.html) and [repo](https://github.com/determined-ai/works-with-determined) did not integrate these data with `cAdvisor` and `dcgm-exporter` to provide usage statistics by individual users or tasks. Further development is required for more precise cluster management.

For example, in [det-state-metrics](https://gpu.lins.lab/prom/det-state-metrics), each job will have an `allocation_id`. With this `allocation_id`, you can get the corresponding `container_id` in `det_container_id_allocation_id`.

With this `container_id`, you can:

- Get `container_runtime_id` in `det_container_id_runtime_container_id`
- Get `gpu_uuid` in `det_gpu_uuid_container_id`

With `container_runtime_id`, you can get container stats of this job with `cAdvisor`;`

With `gpu_uuid`, you can get GPU stats of this job with `dcgm-exporter`.
