### ISSUE TITLE
Harbor can't access

### ISSUE THREAD

**Issue by haobo-song** [LINs-lab/cluster_tutorial#14]
Hi, I want to create a new docker for experiment, but now the Harbor can't access through VPN(harbor.lins.lab). Could someone help to check about it?
<img width="960" alt="image" src="https://user-images.githubusercontent.com/55438357/211562562-0252fe42-ba58-454b-b0a3-8d60f0ad0796.png">

**Comment by tlin-taolin** [comment]
same issue here
<img width="639" alt="image" src="https://user-images.githubusercontent.com/7805823/211563012-591ca4f3-0bfd-422b-94fa-2b957be23ce2.png">

**Comment by haobo-song** [comment]
Also can't login in use shell by docker login -u <username> -p <password> harbor.lins.lab

**Comment by tlin-taolin** [comment]
@DmitriZhao could you please take a look?
