### ISSUE TITLE
Issue of binding directory

### ISSUE THREAD

**Issue by MarcellusZhao** [LINs-lab/cluster_tutorial#15]
I have encountered an issue where the home and data directories are missing after binding on the current 8-gpu available machine. This issue causes a `reading directory '.': Input/output error` error when typing in `ls` command. Under the node, there is `/home` and `/data` directories, but having no other files and folders under both directories.

**Comment by DmitriZhao** [comment]
Sorry for the inconvenience, the problem has been solved.
