### ISSUE TITLE
unhandle error when trying to open a terminal in the notebook

### ISSUE THREAD

**Issue by MarcellusZhao** [LINs-lab/cluster_tutorial#16]
Hello,

I was trying to install a `seaborn` package that does not appear in the pulled image. Firstly, I tried to install it by `pip install seaborn` in the block of notebook, which should work if I remember well, but it showed `OSError: out of pty devices`. Next, I tried to install it in the terminal. but the `unhandle error` stopped me. Before restarting the server, the notebook worked well, so I assume that some unknown error may exist. Could you help me to look into it? Thanks a lot!

Because it will be troublesome and time-consuming to send so many log files to somewhere else, it will be nice to make it work under the LINs server. If it needs much time to fix, I will find another solution then.

**Comment by MarcellusZhao** [comment]
If you need help, e.g., to release some GPUs for test, please let me know. Thanks a lot.

**Comment by DmitriZhao** [comment]
`OSError: out of pty devices` This error has occurred twice. I just updated the Linux kernel and Determined AI, and rebooted the machine. Need to keep watching to see if the error recurs...

**Comment by MarcellusZhao** [comment]
Thanks very much. Notebook can work now.
