### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by tlin-taolin** [LINs-lab/cluster_tutorial#2]
it is ok to use 
```bash
ssh taolin@10.0.2.162
```
to access the node, but it is not the case for 
```bash
ssh -p 22332  taolin@login.lins.lab
```

**Comment by DmitriZhao** [comment]
Duplicate of #1 
P.S. There will be a major update after the arrival of the storage/management node, on which we will migrate and reconfigure the login node, then the user system and NFS share will be double-checked and documented. Closing this for now.
