### ISSUE TITLE
Mount local directory for shell

### ISSUE THREAD

**Issue by MarcellusZhao** [LINs-lab/cluster_tutorial#4]
Hello,

I have an issue of mounting local directory when typing `det shell start --config-file test_task.yaml` under the shell mode. According to the picture introducing how `bind_mounts` works, we can mount `/workspace` and `/datasets` directories by adding relevant commands in the `.yaml` file, right? Pls correct me if I misunderstood it.

But I always came across the same issue as follows,
<img width="1251" alt="微信图片_20221207085020" src="https://user-images.githubusercontent.com/50657356/206119580-b52a1f5e-d42b-4d6e-ba2e-dd7d849c8ad9.png">
This is my `.yaml` file:
<img width="595" alt="微信图片_20221207085208" src="https://user-images.githubusercontent.com/50657356/206119871-bdcc81d0-c8a3-45fa-b981-dc2bf981a3f7.png">

I also tried to use the `-v` augument of `det` to specify the volumn used to mount into docker, but the same issue happened.

Thanks very much for your work!

**Comment by DmitriZhao** [comment]
Hello! Since the storage server has just arrived, we have not yet completed the configuration, and the user's home directory has not been migrated to the shared file system, so it cannot be mounted to the Determined AI cluster node. Till we complete the configuration, feel free to put your code and data to /labdata0/, and you can directly delete those two lines:
```yaml
- host_path: /home/haozhao/
  container_path: /run/determined/workdir/home/
```

**Comment by sp12138** [comment]
I'm not sure why it failed. Maybe you can create a directory under /labdata0, like /labdata0/haozhao. Then retry.

**Comment by MarcellusZhao** [comment]
> I'm not sure why it failed. Maybe you can create a directory under /labdata0, like /labdata0/haozhao. Then retry.

Hello. Thanks for your reply. I could bind mount the local directory for dataset (i.e., `/labdata0`), but failed to mount the directory in my local login node. I will try again after @DmitriZhao completing the configuration. 

Thanks again for your nice work!
