### ISSUE TITLE
determinedAI WebUI dashboard cant open

### ISSUE THREAD

**Issue by haobo-song** [LINs-lab/cluster_tutorial#5]
When using vpn connection, determinedAI WebUI dashboard cant open through Chrome. 
Web address used: https://gpu.lins.lab/
error message: ERR_CONNECTION_REFUSED

**Comment by DmitriZhao** [comment]
Hello, we are asking the school IT services to open VPN access to the new server. You open a port forward to the DeterminedAI dashboard by SSH with this command:

```bash
ssh -NL 8080:10.0.2.168:8080 -p 33322 haobosong@10.0.2.162
```

Then you can access the dashboard by: http://localhost:8080
