### ISSUE TITLE
docker group

### ISSUE THREAD

**Issue by MarcellusZhao** [LINs-lab/cluster_tutorial#8]
Hello,

When I tried to custom an image, it reported following error
<img width="1105" alt="f4f32a9fa3cf865c7c74aebb31a7f77" src="https://user-images.githubusercontent.com/50657356/208001089-cc320419-09ff-4b28-9da9-4184caec5d5f.png">

It seems like we need to create a docker group and add all users into the group, so we can have the access to create new images.

BTW, can we add `apt-get install tmux` in Dockerfile to load tmux module if we dont have `sudo` access?

**Comment by tlin-taolin** [comment]
together with #7, we should create a complete workflow for new users

**Comment by DmitriZhao** [comment]
I have updated the admin's manual and added all users to the `docker` user group. @sp12138

I'm more familiar with the GNU screen, so I assume tmux is the same - You can use it as you want in `docker`.

**Comment by sp12138** [comment]
Be fixed by zhao.
