### ISSUE TITLE
Could not sign in harbor

### ISSUE THREAD

**Issue by gyxxyg** [LINs-lab/cluster_tutorial#9]
I failed to sign in to `harbor.lins.lab`, it seems like I do not have an account (newly created user yesterday).

![image](https://user-images.githubusercontent.com/29498800/208008439-5c782fbb-ec4b-4d71-80b9-16c5e3e338a3.png)

**Comment by sp12138** [comment]
Its issue could be fixed. Can you try again?

**Comment by gyxxyg** [comment]
Resolved, thanks.
